# Generated by Django 6.0.5 on 2026-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите имя бойца')),
                ('photo', models.ImageField(upload_to='fighters/', verbose_name='загрузите фото бойца')),
                ('kindom', models.CharField(choices=[('Земное царство', 'Земное царство'), ('Внешний мир', 'Внешний мир'), ('Преисподняя', 'Преисподняя'), ('Эдения', 'Эдения')], max_length=100, verbose_name='укажите царство')),
                ('description', models.TextField(verbose_name='укажите описание бойца')),
                ('weapon', models.CharField(default='кунай', max_length=100, verbose_name='укажите оружие бойца')),
            ],
        ),
    ]
