# Generated by Django 6.0.5 on 2026-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fighter',
            options={'verbose_name': 'бойца', 'verbose_name_plural': 'бойцы МК'},
        ),
        migrations.AddField(
            model_name='fighter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
