# Generated by Django 6.0.5 on 2026-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_fighter_options_fighter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='fatality',
            field=models.URLField(blank=True, null=True, verbose_name='укажите ссылку на фаталити'),
        ),
    ]
