# Generated by Django 6.0.5 on 2026-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fighter_fatality'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactsMk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.CharField(max_length=100, verbose_name='укажите факт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
