# Generated by Django 6.0.5 on 2026-05-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_car', models.CharField(max_length=100)),
                ('owner_car', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummber', models.CharField(default='0_KG____', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('select_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auto.car')),
            ],
        ),
    ]
