# Generated by Django 6.0.5 on 2026-05-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.CharField(max_length=100)),
                ('choice_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='auto.car')),
            ],
        ),
    ]
