# Generated by Django 6.0.5 on 2026-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_reviewcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcar',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
